# Generated by Django 4.1.1 on 2023-03-09 18:24

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[books.validators.validate_file_size]),
        ),
    ]
